# Generated by Django 3.1 on 2022-04-28 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movies',
        ),
    ]
